### ISSUE TITLE
Support alternative leaderboard services

### ISSUE THREAD

**Issue by ErisApps** [ErisApps/POI#352]
Basically what the title implies, support services other than ScoreSaber so that people who don't wanna use ScoreSaber don't have to...
This includes, but not exhaustive
- AccSaber
- BeatLeader
- Hitbloq
- (Other custom leaderboard services...)

Will require some rework in how the current commands work, maybe completely switch over to slash commands and use command groups instead? (See #177 and #257)

**Comment by ErisApps** [comment]
AccSaber endpoints:
https://api.accsaber.com/categories - Returns the categories they have
https://api.accsaber.com/categories/%7BcategoryName%7D/standings - Category standings
https://api.accsaber.com/ranked-maps - All Ranked Maps
https://api.accsaber.com/ranked-maps/%7BleaderboardId%7D - Returns a specific leaderboard - also works by hash (ScoreSaber leaderboard ID)
https://api.accsaber.com/players/%7BplayerId%7D - Returns a specific player (steam or oculus ID)

**Comment by ErisApps** [comment]
BeatLeader endpoints:
Needs some more digging into the repo. (https://github.com/BeatLeader/beatleader-server/tree/master/Controllers)

**Comment by ErisApps** [comment]
HitBloq endpoints:
Needs some more digging into the repo. (https://github.com/DaFluffyPotato/hitbloq/blob/main/main.py)

**Comment by raineio** [comment]
Regarding AccSaber endpoints. Please add a User Agent, so we can know who or what requested the info.

**Comment by ErisApps** [comment]
The usual format that I use for our lovely bot is `POINext/{Version}`. I hope that's fine for you?
Eg: https://github.com/ErisApps/POI/blob/main/POI.Core/Services/ScoreSaberApiService.cs#L52-L58

**Comment by raineio** [comment]
Yep, that is all good. Thanks! ^^

**Comment by ErisApps** [comment]
This issue will be closed in favor of tickets #445, #446, #447.
